  AWSTemplateFormatVersion: '2010-09-09'
  Transform: AWS::Serverless-2016-10-31
  Description: AWS Serverless Quarkus HTTP - code-with-quarkus-1.0.0-SNAPSHOT
  Globals:
    Api:
      EndpointConfiguration: REGIONAL
      BinaryMediaTypes:
        - "*/*"

  Resources:
    CodeWithQuarkusNative:
      Type: AWS::Serverless::Function
      Properties:
        Handler: not.used.in.provided.runtimei
        Runtime: provided
        CodeUri: build/function.zip
        MemorySize: 3000
        Policies: AWSLambdaBasicExecutionRole
        Timeout: 30
        Environment:
          Variables:
            DISABLE_SIGNAL_HANDLERS: true
        Events:
          HttpApiEvent:
            Type: HttpApi

  Outputs:
    CodeWithQuarkusNativeApi:
      Description: URL for application
      Value: !Sub 'https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/'
      Export:
        Name: CodeWithQuarkusNativeApi
