  AWSTemplateFormatVersion: '2010-09-09'
  Transform: AWS::Serverless-2016-10-31
  Description: AWS Serverless Quarkus HTTP - code-with-quarkus-1.0.0-SNAPSHOT

  Parameters:
    SecurityGroupIds:
      Type: CommaDelimitedList
    SubnetIDs:
      Type: CommaDelimitedList
      Description: list
    ArnCognito:
      Type: String
      Description: arn

  Resources:
    CodeWithQuarkusNative:
      Type: AWS::Serverless::Function
      Properties:
        Handler: not.used.in.provided.runtimei
        Runtime: provided
        CodeUri: build/function.zip
        MemorySize: 3000
        Policies: AWSLambdaBasicExecutionRole
        Timeout: 30
        Environment:
          Variables:
            DISABLE_SIGNAL_HANDLERS: true
        Events:
          HttpApiEvent:
            Type: HttpApi
            Properties:
              ApiId: !Ref HttpApi
        VpcConfig:
          SecurityGroupIds: !Ref SecurityGroupIds
          SubnetIds: !Ref SubnetIDs

    HttpApi:
      Type: AWS::Serverless::HttpApi
      Properties:
        CorsConfiguration:
          AllowOrigins:
            - "*"
          AllowMethods:
            - GET
            - POST
            - PUT
            - DELETE
          AllowCredentials: false
          ExposeHeaders:
            - "*"
            - "application/json"
          AllowHeaders:
            - "*"
            - "origin"
            - "content-type"
            - "accept"
            - "authorization"