version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "QuarkusDev"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1xpwtfuk3wzay"
s3_prefix = "QuarkusDev"
region = "us-east-1"
profile = "aws-temp"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
